"""Add system_prompt fields to ChatbotContent

Revision ID: b70190e2b3b8
Revises: 
Create Date: 2025-05-23 08:42:20.029555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b70190e2b3b8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbot_contents', sa.Column('system_prompt_role', sa.Text(), nullable=True))
    op.add_column('chatbot_contents', sa.Column('system_prompt_guidelines', sa.Text(), nullable=True))
    op.alter_column('chatbot_contents', 'intro_message',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chatbot_contents', 'intro_message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('chatbot_contents', 'system_prompt_guidelines')
    op.drop_column('chatbot_contents', 'system_prompt_role')
    # ### end Alembic commands ###
